# Generated by Django 4.2 on 2025-04-25 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Share your story (up to 2000 characters).', validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Story Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Enter a short title for your recognition story.', max_length=255, verbose_name='Title'),
        ),
    ]
