# Generated by Django 4.2 on 2025-04-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_userprofile_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='department_fk',
            new_name='department',
        ),
    ]
