# Generated by Django 4.2 on 2025-04-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_options'),
        ('profiles', '0007_rename_department_fk_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='department.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='../default_profile_vjekwr', help_text='Upload a square image for best results.', upload_to='images/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='presentation',
            field=models.CharField(blank=True, help_text='Optional short intro, visible on your profile.', max_length=300, verbose_name='User bio / About me'),
        ),
    ]
