# Generated by Django 4.2 on 2025-06-15 20:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Give a short headline for this nomination.', max_length=255, verbose_name='Title')),
                ('content', models.TextField(help_text='Explain why you are nominating this person (up to 2000 characters).', validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Nomination Reason')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations_sent', to=settings.AUTH_USER_MODEL)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations_received', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, help_text='Tag assigned to categorize the nomination.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag', verbose_name='Nomination Tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
