# Generated by Django 5.2 on 2025-04-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='category',
        ),
    ]
