# Generated by Django 5.2 on 2025-04-21 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0003_alter_nomination_content_alter_nomination_tags'),
        ('tags', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='tags',
        ),
        migrations.AddField(
            model_name='nomination',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
            preserve_default=False,
        ),
    ]
