# Generated by Django 4.2 on 2025-04-25 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0005_alter_nomination_content_alter_nomination_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='content',
            field=models.TextField(help_text='Explain why you are nominating this person (up to 2000 characters).', validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Nomination Reason'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='title',
            field=models.CharField(help_text='Give a short headline for this nomination.', max_length=255, verbose_name='Title'),
        ),
    ]
