# Generated by Django 4.2 on 2025-04-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#cccccc', help_text='Hex code (e.g. #FF5733)', max_length=7),
        ),
    ]
