# Generated by Django 5.2 on 2025-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='department_icons/')),
            ],
        ),
    ]
