# Generated by Django 4.2 on 2025-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Short unique code for the department (e.g. ENG, OPS).', max_length=10, unique=True, verbose_name='Department code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional icon representing this department.', null=True, upload_to='images/', verbose_name='Department icon'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Display name for the department (e.g. Engineering, Sales).', max_length=50, unique=True, verbose_name='Department name'),
        ),
    ]
